#? List all tasks by user

# GET http://localhost:3333/task
# Authorization: Bearer {INSERT_YOUR_TOKEN_HERE}

#? Get a task by id

# GET http://localhost:3333/task/{INSERT_TASK_ID_HERE}
# Authorization: Bearer {INSERT_YOUR_TOKEN_HERE}

#? Create a new task

# POST http://localhost:3333/task
# Content-Type: application/json
# Authorization: Bearer {INSERT_YOUR_TOKEN_HERE}

# {
# 	"title":"My task title",
# 	"content":"My task content...."
# }


#? Update a task

# PUT http://localhost:3333/task/{INSERT_TASK_ID_HERE}
# Content-Type: application/json
# Authorization: Bearer {INSERT_YOUR_TOKEN_HERE}

# {
# 	"markAsMaking":true
# }


#? Delete a task

# DELETE http://localhost:3333/task/{INSERT_TASK_ID_HERE}
# Authorization: Bearer {INSERT_YOUR_TOKEN_HERE}